{% set name = "asn1" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c00e37a58d25912dc7c7536770490644ab8e0305f5adc28cf7eebee32e2703c2

build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - enum-compat

test:
  imports:
    - asn1
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/andrivet/python-asn1
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python-ASN1 is a simple ASN.1 encoder and decoder for Python 2.6+ and 3.3+.
  doc_url: https://python-asn1.readthedocs.io/en/latest/
  dev_url: https://github.com/andrivet/python-asn1

extra:
  recipe-maintainers:
    - chrisburr
